Fix GetArrayAsserting in OpAttrs. Right now it causes a failure at build time: undefined reference to tfrt::OpAttrType tfrt::GetOpAttrType<llvm::ArrayRef<int> >() Also, I added a test to validate GetArray.
PiperOrigin-RevId: 311620581