func needs to be replaced with func.func to fix the following compilation errors:
error: custom op 'func' is unknown (tried 'builtin.func' as well)
PiperOrigin-RevId: 463257340